version: '3'

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    image: ter2002/back_img:1.0
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: ter2002/front_img:1.0
