version: '3'

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    image: ter2002/backIMG:1.0
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: ter2002/frontIMG:1.0
