# version: '3'

# services:
#   backend:
#     build:
#       context: ./back
#       dockerfile: Dockerfile
#     image: ter2002/back_img:1.0
#   frontend:
#     build:
#       context: ./front
#       dockerfile: Dockerfile
#     image: ter2002/front_img:1.0
# version is now using "compose spec"
# v2 and v3 are now combined!
# docker-compose v1.27+ required

services:
  fe:
    build: ./front
    image: sorachat2002/fe:lastest
    ports: 
      - 3000:80
    links:
      - be
    networks:
      - front-tier
    

  be:
    build: ./back
    image: sorachat2002/be:lastest
    ports: 
      - 8088:80
    networks:
      - back-tier
  
networks:
  front-tier:
  back-tier:
